//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.3053
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facturanet.WebserviceModule.FacturanetServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FacturanetServiceReference.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Run", ReplyAction="http://tempuri.org/IService/RunResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Facturanet.Server.BaseRequest<Facturanet.Infrastructure.SystemInfoResponse>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Facturanet.Infrastructure.SystemInfoRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Facturanet.Server.BaseRequest<Facturanet.Server.CompositeResponse>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Facturanet.Server.CompositeRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Facturanet.Server.BaseRequest<Facturanet.Business.GetClientsResponse>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Facturanet.Business.GetClientsRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Facturanet.Server.BaseRequest<Facturanet.Business.RemoveProductResponse>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Facturanet.Business.RemoveProductRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Facturanet.Server.BaseRequest<Facturanet.Business.GetInvoiceResponse>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Facturanet.Business.GetInvoiceRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Facturanet.Server.BaseRequest<Facturanet.Business.GetProductsResponse>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Facturanet.Business.GetProductsRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Facturanet.Server.CompositeResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Facturanet.Infrastructure.SystemInfoResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Facturanet.Business.GetClientsResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Facturanet.Business.RemoveProductResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Facturanet.Business.GetProductsResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Facturanet.Business.GetInvoiceResponse))]
        Facturanet.Server.Response Run(Facturanet.Server.Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/RunMock", ReplyAction="http://tempuri.org/IService/RunMockResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Facturanet.Server.BaseRequest<Facturanet.Infrastructure.SystemInfoResponse>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Facturanet.Infrastructure.SystemInfoRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Facturanet.Server.BaseRequest<Facturanet.Server.CompositeResponse>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Facturanet.Server.CompositeRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Facturanet.Server.BaseRequest<Facturanet.Business.GetClientsResponse>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Facturanet.Business.GetClientsRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Facturanet.Server.BaseRequest<Facturanet.Business.RemoveProductResponse>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Facturanet.Business.RemoveProductRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Facturanet.Server.BaseRequest<Facturanet.Business.GetInvoiceResponse>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Facturanet.Business.GetInvoiceRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Facturanet.Server.BaseRequest<Facturanet.Business.GetProductsResponse>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Facturanet.Business.GetProductsRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Facturanet.Server.CompositeResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Facturanet.Infrastructure.SystemInfoResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Facturanet.Business.GetClientsResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Facturanet.Business.RemoveProductResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Facturanet.Business.GetProductsResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Facturanet.Business.GetInvoiceResponse))]
        Facturanet.Server.Response RunMock(Facturanet.Server.Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ForceInit", ReplyAction="http://tempuri.org/IService/ForceInitResponse")]
        void ForceInit();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IServiceChannel : Facturanet.WebserviceModule.FacturanetServiceReference.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<Facturanet.WebserviceModule.FacturanetServiceReference.IService>, Facturanet.WebserviceModule.FacturanetServiceReference.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Facturanet.Server.Response Run(Facturanet.Server.Request request) {
            return base.Channel.Run(request);
        }
        
        public Facturanet.Server.Response RunMock(Facturanet.Server.Request request) {
            return base.Channel.RunMock(request);
        }
        
        public void ForceInit() {
            base.Channel.ForceInit();
        }
    }
}
