// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace FacturaNet.FnGtk {
    
    
    public partial class FrmLogin2 {
        
        private Gtk.VBox boxPrincipal;
        
        private Gtk.VBox boxDatos;
        
        private Gtk.TreeView treeview2;
        
        private Gtk.ComboBoxEntry comboboxentry1;
        
        private Gtk.ComboBox combobox1;
        
        private Gtk.Table tblDatos;
        
        private Gtk.Label laClave;
        
        private Gtk.Label laNombre;
        
        private Gtk.Entry txtClave;
        
        private Gtk.Entry txtNombre;
        
        private Gtk.HButtonBox boxButtons;
        
        private Gtk.Button btnCancelar;
        
        private Gtk.Button btnAceptar;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget FacturaNet.FnGtk.FrmLogin2
            this.Name = "FacturaNet.FnGtk.FrmLogin2";
            this.Title = Mono.Unix.Catalog.GetString("FrmLogin2");
            this.TypeHint = ((Gdk.WindowTypeHint)(1));
            this.WindowPosition = ((Gtk.WindowPosition)(4));
            this.Modal = true;
            this.BorderWidth = ((uint)(5));
            this.DefaultWidth = 300;
            this.DefaultHeight = 100;
            // Container child FacturaNet.FnGtk.FrmLogin2.Gtk.Container+ContainerChild
            this.boxPrincipal = new Gtk.VBox();
            this.boxPrincipal.Name = "boxPrincipal";
            this.boxPrincipal.Spacing = 2;
            // Container child boxPrincipal.Gtk.Box+BoxChild
            this.boxDatos = new Gtk.VBox();
            this.boxDatos.Name = "boxDatos";
            this.boxDatos.Spacing = 6;
            // Container child boxDatos.Gtk.Box+BoxChild
            this.treeview2 = new Gtk.TreeView();
            this.treeview2.HeightRequest = 200;
            this.treeview2.CanFocus = true;
            this.treeview2.Name = "treeview2";
            this.treeview2.HeadersClickable = true;
            this.boxDatos.Add(this.treeview2);
            Gtk.Box.BoxChild w1 = ((Gtk.Box.BoxChild)(this.boxDatos[this.treeview2]));
            w1.Position = 0;
            // Container child boxDatos.Gtk.Box+BoxChild
            this.comboboxentry1 = Gtk.ComboBoxEntry.NewText();
            this.comboboxentry1.Name = "comboboxentry1";
            this.boxDatos.Add(this.comboboxentry1);
            Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.boxDatos[this.comboboxentry1]));
            w2.Position = 1;
            w2.Expand = false;
            w2.Fill = false;
            // Container child boxDatos.Gtk.Box+BoxChild
            this.combobox1 = Gtk.ComboBox.NewText();
            this.combobox1.Name = "combobox1";
            this.boxDatos.Add(this.combobox1);
            Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.boxDatos[this.combobox1]));
            w3.Position = 2;
            w3.Expand = false;
            w3.Fill = false;
            // Container child boxDatos.Gtk.Box+BoxChild
            this.tblDatos = new Gtk.Table(((uint)(2)), ((uint)(2)), false);
            this.tblDatos.Name = "tblDatos";
            this.tblDatos.RowSpacing = ((uint)(4));
            this.tblDatos.ColumnSpacing = ((uint)(4));
            this.tblDatos.BorderWidth = ((uint)(4));
            // Container child tblDatos.Gtk.Table+TableChild
            this.laClave = new Gtk.Label();
            this.laClave.Name = "laClave";
            this.laClave.Xalign = 0F;
            this.laClave.LabelProp = Mono.Unix.Catalog.GetString("Contraseña");
            this.tblDatos.Add(this.laClave);
            Gtk.Table.TableChild w4 = ((Gtk.Table.TableChild)(this.tblDatos[this.laClave]));
            w4.TopAttach = ((uint)(1));
            w4.BottomAttach = ((uint)(2));
            w4.XOptions = ((Gtk.AttachOptions)(4));
            w4.YOptions = ((Gtk.AttachOptions)(4));
            // Container child tblDatos.Gtk.Table+TableChild
            this.laNombre = new Gtk.Label();
            this.laNombre.Name = "laNombre";
            this.laNombre.Xalign = 0F;
            this.laNombre.LabelProp = Mono.Unix.Catalog.GetString("Usuario");
            this.tblDatos.Add(this.laNombre);
            Gtk.Table.TableChild w5 = ((Gtk.Table.TableChild)(this.tblDatos[this.laNombre]));
            w5.XOptions = ((Gtk.AttachOptions)(4));
            w5.YOptions = ((Gtk.AttachOptions)(4));
            // Container child tblDatos.Gtk.Table+TableChild
            this.txtClave = new Gtk.Entry();
            this.txtClave.CanFocus = true;
            this.txtClave.Name = "txtClave";
            this.txtClave.IsEditable = true;
            this.txtClave.Visibility = false;
            this.txtClave.InvisibleChar = '●';
            this.tblDatos.Add(this.txtClave);
            Gtk.Table.TableChild w6 = ((Gtk.Table.TableChild)(this.tblDatos[this.txtClave]));
            w6.TopAttach = ((uint)(1));
            w6.BottomAttach = ((uint)(2));
            w6.LeftAttach = ((uint)(1));
            w6.RightAttach = ((uint)(2));
            w6.YOptions = ((Gtk.AttachOptions)(4));
            // Container child tblDatos.Gtk.Table+TableChild
            this.txtNombre = new Gtk.Entry();
            this.txtNombre.CanFocus = true;
            this.txtNombre.Name = "txtNombre";
            this.txtNombre.IsEditable = true;
            this.txtNombre.InvisibleChar = '●';
            this.tblDatos.Add(this.txtNombre);
            Gtk.Table.TableChild w7 = ((Gtk.Table.TableChild)(this.tblDatos[this.txtNombre]));
            w7.LeftAttach = ((uint)(1));
            w7.RightAttach = ((uint)(2));
            w7.YOptions = ((Gtk.AttachOptions)(4));
            this.boxDatos.Add(this.tblDatos);
            Gtk.Box.BoxChild w8 = ((Gtk.Box.BoxChild)(this.boxDatos[this.tblDatos]));
            w8.Position = 3;
            w8.Expand = false;
            w8.Fill = false;
            this.boxPrincipal.Add(this.boxDatos);
            Gtk.Box.BoxChild w9 = ((Gtk.Box.BoxChild)(this.boxPrincipal[this.boxDatos]));
            w9.Position = 0;
            w9.Expand = false;
            w9.Padding = ((uint)(2));
            // Container child boxPrincipal.Gtk.Box+BoxChild
            this.boxButtons = new Gtk.HButtonBox();
            this.boxButtons.Name = "boxButtons";
            this.boxButtons.Spacing = 4;
            this.boxButtons.BorderWidth = ((uint)(2));
            this.boxButtons.LayoutStyle = ((Gtk.ButtonBoxStyle)(4));
            // Container child boxButtons.Gtk.ButtonBox+ButtonBoxChild
            this.btnCancelar = new Gtk.Button();
            this.btnCancelar.CanDefault = true;
            this.btnCancelar.CanFocus = true;
            this.btnCancelar.Name = "btnCancelar";
            this.btnCancelar.UseStock = true;
            this.btnCancelar.UseUnderline = true;
            this.btnCancelar.Label = "gtk-cancel";
            this.boxButtons.Add(this.btnCancelar);
            Gtk.ButtonBox.ButtonBoxChild w10 = ((Gtk.ButtonBox.ButtonBoxChild)(this.boxButtons[this.btnCancelar]));
            w10.Expand = false;
            w10.Fill = false;
            // Container child boxButtons.Gtk.ButtonBox+ButtonBoxChild
            this.btnAceptar = new Gtk.Button();
            this.btnAceptar.CanDefault = true;
            this.btnAceptar.CanFocus = true;
            this.btnAceptar.Name = "btnAceptar";
            this.btnAceptar.UseStock = true;
            this.btnAceptar.UseUnderline = true;
            this.btnAceptar.Label = "gtk-ok";
            this.boxButtons.Add(this.btnAceptar);
            Gtk.ButtonBox.ButtonBoxChild w11 = ((Gtk.ButtonBox.ButtonBoxChild)(this.boxButtons[this.btnAceptar]));
            w11.Position = 1;
            w11.Expand = false;
            w11.Fill = false;
            this.boxPrincipal.Add(this.boxButtons);
            Gtk.Box.BoxChild w12 = ((Gtk.Box.BoxChild)(this.boxPrincipal[this.boxButtons]));
            w12.Position = 1;
            w12.Expand = false;
            w12.Fill = false;
            this.Add(this.boxPrincipal);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.btnAceptar.HasDefault = true;
            this.Show();
            this.DeleteEvent += new Gtk.DeleteEventHandler(this.OnDeleteEvent);
            this.btnCancelar.Clicked += new System.EventHandler(this.OnBtnCancelarClicked);
            this.btnAceptar.Clicked += new System.EventHandler(this.OnBtnAceptarClicked);
        }
    }
}
